version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  deps: "taskfiles/deps/main.yaml"
  docs: "taskfiles/docs.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"

tasks:
  clean:
    cmds:
      - task: "docs:clean"
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
