version: "3"

vars:
  # Paths
  BUILD_DIR: "{{.TASKFILE_DIR}}/build"
  DOCS_OUTPUT_DIR: "{{.BUILD_DIR}}/html"
  NODE_DEPS_DIR: "{{.BUILD_DIR}}/node"
  VENV_DIR: "{{.BUILD_DIR}}/venv"

  # Other variables
  CHECKSUM_TAR_BASE_ARGS: >-
    --group=0
    --mtime='UTC 1970-01-01'
    --numeric-owner
    --owner=0
    --sort=name

tasks:
  default:
    deps: ["docs"]

  clean:
    cmds:
      - "rm -rf '{{.BUILD_DIR}}'"

  docs:
    deps: ["venv"]
    vars:
      CHECKSUM_FILE: "{{.BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.DOCS_OUTPUT_DIR}}"
    cmds:
      - |
        . "{{.VENV_DIR}}/bin/activate"
        sphinx-build -a -E -c docs -b html docs "{{.OUTPUT_DIR}}"
      # Checksum the generated files (this command must be last)
      - >-
        tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} .
        | md5sum > "{{.CHECKSUM_FILE}}"
    sources:
      - "docs/**/*"
      - "{{.BUILD_DIR}}/venv.md5"
    status:
      - "test -f '{{.CHECKSUM_FILE}}'"
      - >-
        diff
        <(tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} . | md5sum)
        "{{.CHECKSUM_FILE}}"

  download-projects:
    deps: ["venv"]
    cmds:
      - |-
        . "{{.VENV_DIR}}/bin/activate"
        python3 scripts/download-projects.py --build-dir "{{.BUILD_DIR}}"

  release-tar:
    deps: ["docs"]
    vars:
      OUTPUT_DIR_NAME: "yscope-docs-release"
      OUTPUT_DIR: "{{.BUILD_DIR}}/{{.OUTPUT_DIR_NAME}}"
      SITE_PUBLIC_DIR: "{{.OUTPUT_DIR}}/public"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "mkdir -p '{{.OUTPUT_DIR}}'"
      - >-
        rsync
        --archive
        --relative
        conf/projects.json
        server/.env
        server/src
        server/package.json
        server/package-lock.json
        server/README.md
        "{{.OUTPUT_DIR}}"
      - "mkdir '{{.SITE_PUBLIC_DIR}}'"
      - "rsync -a '{{.BUILD_DIR}}/html' {{.SITE_PUBLIC_DIR}}"
      - |-
        cd "{{.BUILD_DIR}}"
        find -type d -regex ".*/build/docs/html" -exec \
          rsync \
          --archive \
          --relative \
          {} \
          "{{.SITE_PUBLIC_DIR}}" \
          \;
      - >-
        tar czf "{{.BUILD_DIR}}/{{.OUTPUT_DIR_NAME}}.tar.gz" --directory "{{.OUTPUT_DIR}}/.."
        "{{.OUTPUT_DIR_NAME}}"

  serve:
    dir: "server"
    deps:
      - "docs"
      - "server"
    cmds:
      - "PUBLIC_DIR='{{.BUILD_DIR}}' npm run dev"

  server:
    internal: true
    dir: "server"
    vars:
      CHECKSUM_FILE: "{{.BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "node_modules"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "npm install"
      # Checksum the generated files (this command must be last)
      - >-
        tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} .
        | md5sum > "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.TASKFILE}}"
      - "package.json"
    status:
      - "test -f '{{.CHECKSUM_FILE}}'"
      - >-
        diff
        <(tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} . | md5sum)
        "{{.CHECKSUM_FILE}}"

  venv:
    internal: true
    vars:
      CHECKSUM_FILE: "{{.BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.VENV_DIR}}"
    cmds:
      - "rm -rf '{{.OUTPUT_DIR}}'"
      - "python3 -m venv '{{.OUTPUT_DIR}}'"
      # Remove calls to `hash` since Task uses `gosh` rather than `bash`.
      # NOTE: Older versions of Python's venv would only call `hash` if they detected the running
      # shell was one that had the command, but that's not the case in newer versions.
      - "sed -i 's/^\\s*hash\\s\\+.*//g' '{{.OUTPUT_DIR}}/bin/activate'"
      - |-
        . "{{.OUTPUT_DIR}}/bin/activate"
        pip3 install --upgrade -r requirements.txt
      # Checksum the generated files (this command must be last)
      - >-
        tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} .
        | md5sum > "{{.CHECKSUM_FILE}}"
    sources:
      - "{{.TASKFILE}}"
      - "requirements.txt"
    status:
      - "test -f '{{.CHECKSUM_FILE}}'"
      - >-
        diff
        <(tar cf - --directory "{{.OUTPUT_DIR}}" {{.CHECKSUM_TAR_BASE_ARGS}} . | md5sum)
        "{{.CHECKSUM_FILE}}"
